### ISSUE TITLE
Ghost AI

### ISSUE THREAD

**Issue by GameCrazed** [GameCrazed/SEGP2_PacmanApp#7]
AI that controls where and how the ghosts navigate the maze needs to be written and implemented so that the player has something to compete with. particular care should be given to ensure that the AI is not so difficult that it makes the game unbeatable, but not so easy that it isn't a challenge.

**Comment by Yahya-Said** [comment]
Tried to start creating the AI however it was quiet difficult moving ghosts within the enclosure at a slow speed. I did manage to get them moving around the edge of the maze however the ghosts were moving too fast and were more like blinking ghosts due to their speed. My approach was to use the positions in the two-dimentional array to move ghosts and this was to make sure that we could locate positions of both pac-man and the ghost at the same time in order to find out if they are both in the same position so that we can end the game. However a different approach will have to be used.

**Comment by GameCrazed** [comment]
Ghosts now aimlessly move throughout the maze and are capable of killing Pacman, however AI has yet to be implemented.

**Comment by GameCrazed** [comment]
Ai has been implemented through a group effort between Yahya, Connor & myself. There are still some finalisations to be made but ghosts now track Pacman and are capable of killing him.

**Comment by Yahya-Said** [comment]
Ai now follows pacman but also has the ability to move randomly when it reaches a junction. Each ghost has a different probability which chooses between following pacman or moving randomly at that junction.
